/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/icons8_lego_heart.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/icons8_lego_heart.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.icons8_lego_heart.geometry} material={materials.icons8_lego_heart} position={[0, 1.984, 0]} />
    </group>
  )
}

useGLTF.preload('/icons8_lego_heart.glb')
