name: Deploy React App via FTP

on:
  push:
    branches:
      - deploy
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22' 
      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.cloud09.id
          username: ${{ secrets.FTP_USERNAME }}  # Menggunakan username dari secrets
          password: ${{ secrets.FTP_PASSWORD }}  # Menggunakan password dari secrets
          local-dir: ./build/  # Direktori lokal tempat hasil build
          server-dir: ./public_html/ 
